# Finding the important dataset

In [52]:
import pandas as pd

In [53]:
df = pd.read_csv("dataset.csv")
# df.columns

In [54]:
df.head()

,MonthEndDate,SSN_id,SSNJoint_id,Account_id,MostRecentLinkedCard_id,CreditCard_id,CardType,CardNumberTransferDate,OpenDate,CreditLine,...,LifetimeDelinquent1CycleCount,LifetimeDelinquent2CycleCount,LifetimeDelinquent3CycleCount,LifetimeDelinquent4CycleCount,LifetimeDelinquent5CycleCount,LifetimeDelinquent6CycleCount,LifetimeDelinquent7CycleCount,ChargeOffDate,ChargeOffAmount,Target
0,7/31/2021,C4E52479-A99F-4D1F-89CA-A7E24565FEA0,NaN,EF24033A-BF83-4757-B8EB-892AA8653974,0F917AAB-C5A2-47E8-9822-5EF646436782,0F917AAB-C5A2-47E8-9822-5EF646436782,VISA PLATINUM,NaN,8/21/2019,18000,...,0,0,0,0,0,0,0,NaN,0,0
1,6/30/2021,C4E52479-A99F-4D1F-89CA-A7E24565FEA0,NaN,EF24033A-BF83-4757-B8EB-892AA8653974,0F917AAB-C5A2-47E8-9822-5EF646436782,0F917AAB-C5A2-47E8-9822-5EF646436782,VISA PLATINUM,NaN,8/21/2019,18000,...,0,0,0,0,0,0,0,NaN,0,0
2,5/31/2021,C4E52479-A99F-4D1F-89CA-A7E24565FEA0,NaN,EF24033A-BF83-4757-B8EB-892AA8653974,0F917AAB-C5A2-47E8-9822-5EF646436782,0F917AAB-C5A2-47E8-9822-5EF646436782,VISA PLATINUM,NaN,8/21/2019,18000,...,0,0,0,0,0,0,0,NaN,0,0
3,4/30/2021,C4E52479-A99F-4D1F-89CA-A7E24565FEA0,NaN,EF24033A-BF83-4757-B8EB-892AA8653974,0F917AAB-C5A2-47E8-9822-5EF646436782,0F917AAB-C5A2-47E8-9822-5EF646436782,VISA PLATINUM,NaN,8/21/2019,18000,...,0,0,0,0,0,0,0,NaN,0,0
4,3/31/2021,C4E52479-A99F-4D1F-89CA-A7E24565FEA0,NaN,EF24033A-BF83-4757-B8EB-892AA8653974,0F917AAB-C5A2-47E8-9822-5EF646436782,0F917AAB-C5A2-47E8-9822-5EF646436782,VISA PLATINUM,NaN,8/21/2019,18000,...,0,0,0,0,0,0,0,NaN,0,0

# Separating the important features from the original dataset

In [55]:
imp_Cardtypefeatures = df.loc[:, [
                             'CardType',
                             'CreditLine',
                             'LastStatementBalanceAmount',
                             'LastStatementPurchaseAmount', 
                             'LastStatementPurchaseReturnAmount',
                             'LastStatementMinimumPaymentDueAmount',
                             'LastStatementPaymentTotalAmount',
                             'CardExternalStatus',
                             'CardInternalStatus',
                             'ActivityHistory1_12',
                             'DelinquentDaysCount',
                             'DelinquentTotalAmount',
                             'LifetimeDelinquent1CycleCount',
                             'LifetimeDelinquent2CycleCount',
                             'LifetimeDelinquent3CycleCount',
                             'LifetimeDelinquent4CycleCount',
                             'LifetimeDelinquent5CycleCount',
                             'LifetimeDelinquent6CycleCount',
                             'LifetimeDelinquent7CycleCount',
                             'ChargeOffAmount',
                              'Target'
]
                            ]

In [56]:
imp_Cardtypefeatures

,CardType,CreditLine,LastStatementBalanceAmount,LastStatementPurchaseAmount,LastStatementPurchaseReturnAmount,LastStatementMinimumPaymentDueAmount,LastStatementPaymentTotalAmount,CardExternalStatus,CardInternalStatus,ActivityHistory1_12,...,DelinquentTotalAmount,LifetimeDelinquent1CycleCount,LifetimeDelinquent2CycleCount,LifetimeDelinquent3CycleCount,LifetimeDelinquent4CycleCount,LifetimeDelinquent5CycleCount,LifetimeDelinquent6CycleCount,LifetimeDelinquent7CycleCount,ChargeOffAmount,Target
0,VISA PLATINUM,18000,4710.24,0.00,0,141,1000.00,Active,Active,IIIIIIIIIIII,...,0,0,0,0,0,0,0,0,0,0
1,VISA PLATINUM,18000,5672.74,0.00,0,0,1000.00,Active,Active,IIIIIIIIIIII,...,0,0,0,0,0,0,0,0,0,0
2,VISA PLATINUM,18000,6628.99,0.00,0,199,1000.00,Active,Active,IIIIIIIIIIII,...,0,0,0,0,0,0,0,0,0,0
3,VISA PLATINUM,18000,7577.10,0.00,0,0,1000.00,Active,Active,IIIIIIIIIIII,...,0,0,0,0,0,0,0,0,0,0
4,VISA PLATINUM,18000,8518.43,0.00,0,256,1000.00,Active,Active,IIIIIIIIIIII,...,0,0,0,0,0,0,0,0,0,0
5,VISA PLATINUM,18000,9453.96,0.00,0,284,600.00,Active,Active,IIIIIIIIIIII,...,0,0,0,0,0,0,0,0,0,0
6,VISA PLATINUM,18000,9983.57,0.00,0,300,500.00,Active,Active,IIIIIIIIIIII,...,0,0,0,0,0,0,0,0,0,0
7,VISA PLATINUM,18000,10409.66,0.00,0,0,500.00,Active,Active,IIIIIIIIIIII,...,0,0,0,0,0,0,0,0,0,0
8,VISA PLATINUM,18000,10832.62,0.00,0,325,400.00,Active,Active,IIIIIIIIIIII,...,0,0,0,0,0,0,0,0,0,0
9,VISA PLATINUM,18000,11152.88,0.00,0,335,400.00,Active,Active,IIIIIIIIIIII,...,0,0,0,0,0,0,0,0,0,0
10,VISA PLATINUM,18000,11470.92,0.00,0,344,352.00,Active,Active,IIIIIIIIIIII,...,0,0,0,0,0,0,0,0,0,0
11,VISA PLATINUM,18000,11738.51,0.00,0,352,500.00,Active,Active,IIIIIIIIIIIA,...,0,0,0,0,0,0,0,0,0,0
12,VISA PLATINUM,18000,12218.70,0.00,0,367,500.00,Active,Active,IIIIIIIIIIA,...,0,0,0,0,0,0,0,0,0,0
13,VISA PLATINUM,18000,12698.08,0.00,0,0,500.00,Active,Active,IIIIIIIIIA,...,0,0,0,0,0,0,0,0,0,0
14,VISA PLATINUM,18000,13176.73,0.00,0,395,500.00,Active,Active,IIIIIIIIA,...,0,0,0,0,0,0,0,0,0,0
15,VISA PLATINUM,18000,13654.55,0.00,0,0,500.00,Active,Active,IIIIIIIA,...,0,0,0,0,0,0,0,0,0,0
16,VISA PLATINUM,18000,14131.54,0.00,0,424,500.00,Active,Active,IIIIIIA,...,0,0,0,0,0,0,0,0,0,0
17,VISA PLATINUM,18000,14607.60,0.00,0,438,500.00,Active,Active,IIIIIA,...,0,0,0,0,0,0,0,0,0,0
18,VISA PLATINUM,18000,15083.03,0.00,0,452,480.00,Active,Active,IIIIA,...,0,0,0,0,0,0,0,0,0,0
19,VISA PLATINUM,18000,15537.53,0.00,0,0,480.00,Active,Active,IIIA,...,0,0,0,0,0,0,0,0,0,0
20,VISA PLATINUM,18000,15991.29,0.00,0,480,494.00,Active,Active,IIA,...,0,0,0,0,0,0,0,0,0,0
21,VISA PLATINUM,18000,16458.26,0.00,0,494,508.00,Active,Active,IA,...,0,0,0,0,0,0,0,0,0,0
22,VISA PLATINUM,9000,1060.12,44.95,0,32,250.00,Active,Active,QQAQQQQQQA%%,...,0,2,0,0,0,0,0,0,0,0
23,VISA PLATINUM,9000,1256.64,211.38,0,0,300.00,Active,Active,QAQQQQQQA%%%,...,0,2,0,0,0,0,0,0,0,0
24,VISA PLATINUM,9000,1334.93,206.23,0,40,0.00,Active,Active,AQQQQQQA%%%-,...,0,2,0,0,0,0,0,0,0,0
25,VISA PLATINUM,9000,1119.94,738.70,0,0,50.00,Active,Active,QQQQQQA%%%-0,...,0,2,0,0,0,0,0,0,0,0
26,VISA PLATINUM,9000,425.59,161.10,0,27,160.00,Active,Active,QQQQQA%%%-0I,...,0,2,0,0,0,0,0,0,0,0
27,VISA PLATINUM,9000,421.67,324.00,0,27,100.00,Active,Active,QQQQA%%%-0II,...,0,2,0,0,0,0,0,0,0,0
28,VISA PLATINUM,9000,196.28,21.62,0,27,300.00,Active,Active,QQQA%%%-0IIQ,...,0,2,0,0,0,0,0,0,0,0
29,VISA PLATINUM,9000,472.40,131.44,0,0,100.00,Active,Active,QQA%%%-0IIQQ,...,0,2,0,0,0,0,0,0,0,0
30,VISA PLATINUM,9000,437.83,267.51,0,27,100.00,Active,Active,QA%%%-0IIQQQ,...,0,2,0,0,0,0,0,0,0,0
31,VISA PLATINUM,9000,267.61,268.81,0,27,0.00,Active,Active,A%%%-0IIQQQQ,...,0,2,0,0,0,0,0,0,0,0
32,VISA PLATINUM,9000,-1.20,0.00,0,0,0.00,Active,Credit Balance,%%%-0IIQQQQI,...,0,2,0,0,0,0,0,0,0,0
33,VISA PLATINUM,9000,-1.20,0.00,0,0,0.00,Active,Credit Balance,%%-0IIQQQQII,...,0,2,0,0,0,0,0,0,0,0
34,VISA PLATINUM,9000,-1.20,0.00,0,0,0.00,Active,Credit Balance,%-0IIQQQQIII,...,0,2,0,0,0,0,0,0,0,0
35,VISA PLATINUM,9000,-1.20,0.00,0,0,765.81,Active,Credit Balance,-0IIQQQQIII0,...,0,2,0,0,0,0,0,0,0,0
36,VISA PLATINUM,9000,763.04,0.00,0,27,0.00,Active,Credit Balance,0IIQQQQIII0I,...,0,2,0,0,0,0,0,0,0,0
37,VISA PLATINUM,9000,755.42,0.00,0,0,40.00,Active,Active,IIQQQQIII0II,...,0,2,0,0,0,0,0,0,0,0
38,VISA PLATINUM,9000,787.60,0.00,0,27,30.00,Active,Active,IQQQQIII0IIA,...,0,2,0,0,0,0,0,0,0,0
39,VISA PLATINUM,9000,812.14,363.10,0,27,60.00,Active,Active,QQQQIII0IIAZ,...,0,2,0,0,0,0,0,0,0,0
40,VISA PLATINUM,9000,506.48,502.61,0,27,7541.20,Active,Active,QQQIII0IIAZI,...,0,2,0,0,0,0,0,0,0,0
41,VISA PLATINUM,9000,7541.20,375.73,0,0,250.00,Active,Active,QQIII0IIAZII,...,0,2,0,0,0,0,0,0,0,0
42,VISA PLATINUM,9000,7396.55,222.85,0,222,230.00,Active,Active,QIII0IIAZII1,...,0,2,0,0,0,0,0,0,0,0
43,VISA PLATINUM,9000,7391.34,0.00,0,222,300.00,Active,Active,III0IIAZII1I,...,0,2,0,0,0,0,0,0,0,0
44,VISA PLATINUM,9000,7678.81,0.00,0,230,237.00,Active,Active,II0IIAZII1II,...,0,2,0,0,0,0,0,0,0,0
45,VISA PLATINUM,9000,7902.97,0.00,0,237,260.00,Active,Active,I0IIAZII1III,...,0,2,0,0,0,0,0,0,0,0
46,VISA PLATINUM,9000,8149.68,0.00,0,244,0.00,Active,Active,0IIAZII1IIIQ,...,0,2,0,0,0,0,0,0,0,0
47,VISA PLATINUM,2000,83.90,83.90,0,29,0.00,Active,Active,AZZQQZZQ%-ZZ,...,0,0,0,0,0,0,0,0,0,0
48,VISA PLATINUM,2000,0.00,0.00,0,0,0.00,Active,Active,ZZQQZZQ%-ZZZ,...,0,0,0,0,0,0,0,0,0,0

In [36]:
# df

In [57]:
# result = []
for i in range(12):
#     print(i)
    save_str = ("ActivityHistory_%2d" % (i+1)).replace(' ', '')
    imp_Cardtypefeatures[save_str] = ""
imp_Cardtypefeatures

,CardType,CreditLine,LastStatementBalanceAmount,LastStatementPurchaseAmount,LastStatementPurchaseReturnAmount,LastStatementMinimumPaymentDueAmount,LastStatementPaymentTotalAmount,CardExternalStatus,CardInternalStatus,ActivityHistory1_12,...,ActivityHistory_3,ActivityHistory_4,ActivityHistory_5,ActivityHistory_6,ActivityHistory_7,ActivityHistory_8,ActivityHistory_9,ActivityHistory_10,ActivityHistory_11,ActivityHistory_12
0,VISA PLATINUM,18000,4710.24,0.00,0,141,1000.00,Active,Active,IIIIIIIIIIII,...,,,,,,,,,,
1,VISA PLATINUM,18000,5672.74,0.00,0,0,1000.00,Active,Active,IIIIIIIIIIII,...,,,,,,,,,,
2,VISA PLATINUM,18000,6628.99,0.00,0,199,1000.00,Active,Active,IIIIIIIIIIII,...,,,,,,,,,,
3,VISA PLATINUM,18000,7577.10,0.00,0,0,1000.00,Active,Active,IIIIIIIIIIII,...,,,,,,,,,,
4,VISA PLATINUM,18000,8518.43,0.00,0,256,1000.00,Active,Active,IIIIIIIIIIII,...,,,,,,,,,,
5,VISA PLATINUM,18000,9453.96,0.00,0,284,600.00,Active,Active,IIIIIIIIIIII,...,,,,,,,,,,
6,VISA PLATINUM,18000,9983.57,0.00,0,300,500.00,Active,Active,IIIIIIIIIIII,...,,,,,,,,,,
7,VISA PLATINUM,18000,10409.66,0.00,0,0,500.00,Active,Active,IIIIIIIIIIII,...,,,,,,,,,,
8,VISA PLATINUM,18000,10832.62,0.00,0,325,400.00,Active,Active,IIIIIIIIIIII,...,,,,,,,,,,
9,VISA PLATINUM,18000,11152.88,0.00,0,335,400.00,Active,Active,IIIIIIIIIIII,...,,,,,,,,,,
10,VISA PLATINUM,18000,11470.92,0.00,0,344,352.00,Active,Active,IIIIIIIIIIII,...,,,,,,,,,,
11,VISA PLATINUM,18000,11738.51,0.00,0,352,500.00,Active,Active,IIIIIIIIIIIA,...,,,,,,,,,,
12,VISA PLATINUM,18000,12218.70,0.00,0,367,500.00,Active,Active,IIIIIIIIIIA,...,,,,,,,,,,
13,VISA PLATINUM,18000,12698.08,0.00,0,0,500.00,Active,Active,IIIIIIIIIA,...,,,,,,,,,,
14,VISA PLATINUM,18000,13176.73,0.00,0,395,500.00,Active,Active,IIIIIIIIA,...,,,,,,,,,,
15,VISA PLATINUM,18000,13654.55,0.00,0,0,500.00,Active,Active,IIIIIIIA,...,,,,,,,,,,
16,VISA PLATINUM,18000,14131.54,0.00,0,424,500.00,Active,Active,IIIIIIA,...,,,,,,,,,,
17,VISA PLATINUM,18000,14607.60,0.00,0,438,500.00,Active,Active,IIIIIA,...,,,,,,,,,,
18,VISA PLATINUM,18000,15083.03,0.00,0,452,480.00,Active,Active,IIIIA,...,,,,,,,,,,
19,VISA PLATINUM,18000,15537.53,0.00,0,0,480.00,Active,Active,IIIA,...,,,,,,,,,,
20,VISA PLATINUM,18000,15991.29,0.00,0,480,494.00,Active,Active,IIA,...,,,,,,,,,,
21,VISA PLATINUM,18000,16458.26,0.00,0,494,508.00,Active,Active,IA,...,,,,,,,,,,
22,VISA PLATINUM,9000,1060.12,44.95,0,32,250.00,Active,Active,QQAQQQQQQA%%,...,,,,,,,,,,
23,VISA PLATINUM,9000,1256.64,211.38,0,0,300.00,Active,Active,QAQQQQQQA%%%,...,,,,,,,,,,
24,VISA PLATINUM,9000,1334.93,206.23,0,40,0.00,Active,Active,AQQQQQQA%%%-,...,,,,,,,,,,
25,VISA PLATINUM,9000,1119.94,738.70,0,0,50.00,Active,Active,QQQQQQA%%%-0,...,,,,,,,,,,
26,VISA PLATINUM,9000,425.59,161.10,0,27,160.00,Active,Active,QQQQQA%%%-0I,...,,,,,,,,,,
27,VISA PLATINUM,9000,421.67,324.00,0,27,100.00,Active,Active,QQQQA%%%-0II,...,,,,,,,,,,
28,VISA PLATINUM,9000,196.28,21.62,0,27,300.00,Active,Active,QQQA%%%-0IIQ,...,,,,,,,,,,
29,VISA PLATINUM,9000,472.40,131.44,0,0,100.00,Active,Active,QQA%%%-0IIQQ,...,,,,,,,,,,
30,VISA PLATINUM,9000,437.83,267.51,0,27,100.00,Active,Active,QA%%%-0IIQQQ,...,,,,,,,,,,
31,VISA PLATINUM,9000,267.61,268.81,0,27,0.00,Active,Active,A%%%-0IIQQQQ,...,,,,,,,,,,
32,VISA PLATINUM,9000,-1.20,0.00,0,0,0.00,Active,Credit Balance,%%%-0IIQQQQI,...,,,,,,,,,,
33,VISA PLATINUM,9000,-1.20,0.00,0,0,0.00,Active,Credit Balance,%%-0IIQQQQII,...,,,,,,,,,,
34,VISA PLATINUM,9000,-1.20,0.00,0,0,0.00,Active,Credit Balance,%-0IIQQQQIII,...,,,,,,,,,,
35,VISA PLATINUM,9000,-1.20,0.00,0,0,765.81,Active,Credit Balance,-0IIQQQQIII0,...,,,,,,,,,,
36,VISA PLATINUM,9000,763.04,0.00,0,27,0.00,Active,Credit Balance,0IIQQQQIII0I,...,,,,,,,,,,
37,VISA PLATINUM,9000,755.42,0.00,0,0,40.00,Active,Active,IIQQQQIII0II,...,,,,,,,,,,
38,VISA PLATINUM,9000,787.60,0.00,0,27,30.00,Active,Active,IQQQQIII0IIA,...,,,,,,,,,,
39,VISA PLATINUM,9000,812.14,363.10,0,27,60.00,Active,Active,QQQQIII0IIAZ,...,,,,,,,,,,
40,VISA PLATINUM,9000,506.48,502.61,0,27,7541.20,Active,Active,QQQIII0IIAZI,...,,,,,,,,,,
41,VISA PLATINUM,9000,7541.20,375.73,0,0,250.00,Active,Active,QQIII0IIAZII,...,,,,,,,,,,
42,VISA PLATINUM,9000,7396.55,222.85,0,222,230.00,Active,Active,QIII0IIAZII1,...,,,,,,,,,,
43,VISA PLATINUM,9000,7391.34,0.00,0,222,300.00,Active,Active,III0IIAZII1I,...,,,,,,,,,,
44,VISA PLATINUM,9000,7678.81,0.00,0,230,237.00,Active,Active,II0IIAZII1II,...,,,,,,,,,,
45,VISA PLATINUM,9000,7902.97,0.00,0,237,260.00,Active,Active,I0IIAZII1III,...,,,,,,,,,,
46,VISA PLATINUM,9000,8149.68,0.00,0,244,0.00,Active,Active,0IIAZII1IIIQ,...,,,,,,,,,,
47,VISA PLATINUM,2000,83.90,83.90,0,29,0.00,Active,Active,AZZQQZZQ%-ZZ,...,,,,,,,,,,
48,VISA PLATINUM,2000,0.00,0.00,0,0,0.00,Active,Active,ZZQQZZQ%-ZZZ,...,,,,,,,,,,

##### Dictionary to assign values related to the activityhistory1_12 feature

In [58]:
dict = {
     "0"   : "10",
     "1"   : "-150",
     "2"   : "-160",
     "3"   : "-170",
     "4"   : "-180",
     "5"   : "-190",
     "6"   : "200",
     "7"   : "210",
    "A" : "20",
    "B" : "-220",
    "C" : "-230",
    "D" : "-240",
    "E" : "-250",
    "F" : "-260",
    "G" : "-270",
    "H" : "-280",
    "I" : "50",
    "J" : "-10",
    "K" : "-20",
    "L" : "-30",
    "M" : "-40",
    "N" : "-50",
    "O" : "-60",
    "P" :"-70",
    "Q" : "40",
    "R" : "-80",
    "S" : "-90",
    "T" : "-100",
    "U" : "-110",
    "V" : "-120",
    "W" : "-130",
    "X" : "-140",
    "Z" : "0",
    "%" : "10",
    "#" : "20", 
    "+" : "30",
    "-" : "40"    
}

In [59]:
dict

{'0': '10',
 '1': '-150',
 '2': '-160',
 '3': '-170',
 '4': '-180',
 '5': '-190',
 '6': '200',
 '7': '210',
 'A': '20',
 'B': '-220',
 'C': '-230',
 'D': '-240',
 'E': '-250',
 'F': '-260',
 'G': '-270',
 'H': '-280',
 'I': '50',
 'J': '-10',
 'K': '-20',
 'L': '-30',
 'M': '-40',
 'N': '-50',
 'O': '-60',
 'P': '-70',
 'Q': '40',
 'R': '-80',
 'S': '-90',
 'T': '-100',
 'U': '-110',
 'V': '-120',
 'W': '-130',
 'X': '-140',
 'Z': '0',
 '%': '10',
 '#': '20',
 '+': '30',
 '-': '40'}

In [44]:
imp_Cardtypefeatures

,CardType,CreditLine,LastStatementBalanceAmount,LastStatementPurchaseAmount,LastStatementPurchaseReturnAmount,LastStatementMinimumPaymentDueAmount,LastStatementPaymentTotalAmount,CardExternalStatus,CardInternalStatus,ActivityHistory1_12,...,ActivityHistory_3,ActivityHistory_4,ActivityHistory_5,ActivityHistory_6,ActivityHistory_7,ActivityHistory_8,ActivityHistory_9,ActivityHistory_10,ActivityHistory_11,ActivityHistory_12
0,VISA PLATINUM,18000,4710.24,0.00,0,141,1000.00,Active,Active,IIIIIIIIIIII,...,,,,,,,,,,
1,VISA PLATINUM,18000,5672.74,0.00,0,0,1000.00,Active,Active,IIIIIIIIIIII,...,,,,,,,,,,
2,VISA PLATINUM,18000,6628.99,0.00,0,199,1000.00,Active,Active,IIIIIIIIIIII,...,,,,,,,,,,
3,VISA PLATINUM,18000,7577.10,0.00,0,0,1000.00,Active,Active,IIIIIIIIIIII,...,,,,,,,,,,
4,VISA PLATINUM,18000,8518.43,0.00,0,256,1000.00,Active,Active,IIIIIIIIIIII,...,,,,,,,,,,
5,VISA PLATINUM,18000,9453.96,0.00,0,284,600.00,Active,Active,IIIIIIIIIIII,...,,,,,,,,,,
6,VISA PLATINUM,18000,9983.57,0.00,0,300,500.00,Active,Active,IIIIIIIIIIII,...,,,,,,,,,,
7,VISA PLATINUM,18000,10409.66,0.00,0,0,500.00,Active,Active,IIIIIIIIIIII,...,,,,,,,,,,
8,VISA PLATINUM,18000,10832.62,0.00,0,325,400.00,Active,Active,IIIIIIIIIIII,...,,,,,,,,,,
9,VISA PLATINUM,18000,11152.88,0.00,0,335,400.00,Active,Active,IIIIIIIIIIII,...,,,,,,,,,,
10,VISA PLATINUM,18000,11470.92,0.00,0,344,352.00,Active,Active,IIIIIIIIIIII,...,,,,,,,,,,
11,VISA PLATINUM,18000,11738.51,0.00,0,352,500.00,Active,Active,IIIIIIIIIIIA,...,,,,,,,,,,
12,VISA PLATINUM,18000,12218.70,0.00,0,367,500.00,Active,Active,IIIIIIIIIIA,...,,,,,,,,,,
13,VISA PLATINUM,18000,12698.08,0.00,0,0,500.00,Active,Active,IIIIIIIIIA,...,,,,,,,,,,
14,VISA PLATINUM,18000,13176.73,0.00,0,395,500.00,Active,Active,IIIIIIIIA,...,,,,,,,,,,
15,VISA PLATINUM,18000,13654.55,0.00,0,0,500.00,Active,Active,IIIIIIIA,...,,,,,,,,,,
16,VISA PLATINUM,18000,14131.54,0.00,0,424,500.00,Active,Active,IIIIIIA,...,,,,,,,,,,
17,VISA PLATINUM,18000,14607.60,0.00,0,438,500.00,Active,Active,IIIIIA,...,,,,,,,,,,
18,VISA PLATINUM,18000,15083.03,0.00,0,452,480.00,Active,Active,IIIIA,...,,,,,,,,,,
19,VISA PLATINUM,18000,15537.53,0.00,0,0,480.00,Active,Active,IIIA,...,,,,,,,,,,
20,VISA PLATINUM,18000,15991.29,0.00,0,480,494.00,Active,Active,IIA,...,,,,,,,,,,
21,VISA PLATINUM,18000,16458.26,0.00,0,494,508.00,Active,Active,IA,...,,,,,,,,,,
22,VISA PLATINUM,9000,1060.12,44.95,0,32,250.00,Active,Active,QQAQQQQQQA%%,...,,,,,,,,,,
23,VISA PLATINUM,9000,1256.64,211.38,0,0,300.00,Active,Active,QAQQQQQQA%%%,...,,,,,,,,,,
24,VISA PLATINUM,9000,1334.93,206.23,0,40,0.00,Active,Active,AQQQQQQA%%%-,...,,,,,,,,,,
25,VISA PLATINUM,9000,1119.94,738.70,0,0,50.00,Active,Active,QQQQQQA%%%-0,...,,,,,,,,,,
26,VISA PLATINUM,9000,425.59,161.10,0,27,160.00,Active,Active,QQQQQA%%%-0I,...,,,,,,,,,,
27,VISA PLATINUM,9000,421.67,324.00,0,27,100.00,Active,Active,QQQQA%%%-0II,...,,,,,,,,,,
28,VISA PLATINUM,9000,196.28,21.62,0,27,300.00,Active,Active,QQQA%%%-0IIQ,...,,,,,,,,,,
29,VISA PLATINUM,9000,472.40,131.44,0,0,100.00,Active,Active,QQA%%%-0IIQQ,...,,,,,,,,,,
30,VISA PLATINUM,9000,437.83,267.51,0,27,100.00,Active,Active,QA%%%-0IIQQQ,...,,,,,,,,,,
31,VISA PLATINUM,9000,267.61,268.81,0,27,0.00,Active,Active,A%%%-0IIQQQQ,...,,,,,,,,,,
32,VISA PLATINUM,9000,-1.20,0.00,0,0,0.00,Active,Credit Balance,%%%-0IIQQQQI,...,,,,,,,,,,
33,VISA PLATINUM,9000,-1.20,0.00,0,0,0.00,Active,Credit Balance,%%-0IIQQQQII,...,,,,,,,,,,
34,VISA PLATINUM,9000,-1.20,0.00,0,0,0.00,Active,Credit Balance,%-0IIQQQQIII,...,,,,,,,,,,
35,VISA PLATINUM,9000,-1.20,0.00,0,0,765.81,Active,Credit Balance,-0IIQQQQIII0,...,,,,,,,,,,
36,VISA PLATINUM,9000,763.04,0.00,0,27,0.00,Active,Credit Balance,0IIQQQQIII0I,...,,,,,,,,,,
37,VISA PLATINUM,9000,755.42,0.00,0,0,40.00,Active,Active,IIQQQQIII0II,...,,,,,,,,,,
38,VISA PLATINUM,9000,787.60,0.00,0,27,30.00,Active,Active,IQQQQIII0IIA,...,,,,,,,,,,
39,VISA PLATINUM,9000,812.14,363.10,0,27,60.00,Active,Active,QQQQIII0IIAZ,...,,,,,,,,,,
40,VISA PLATINUM,9000,506.48,502.61,0,27,7541.20,Active,Active,QQQIII0IIAZI,...,,,,,,,,,,
41,VISA PLATINUM,9000,7541.20,375.73,0,0,250.00,Active,Active,QQIII0IIAZII,...,,,,,,,,,,
42,VISA PLATINUM,9000,7396.55,222.85,0,222,230.00,Active,Active,QIII0IIAZII1,...,,,,,,,,,,
43,VISA PLATINUM,9000,7391.34,0.00,0,222,300.00,Active,Active,III0IIAZII1I,...,,,,,,,,,,
44,VISA PLATINUM,9000,7678.81,0.00,0,230,237.00,Active,Active,II0IIAZII1II,...,,,,,,,,,,
45,VISA PLATINUM,9000,7902.97,0.00,0,237,260.00,Active,Active,I0IIAZII1III,...,,,,,,,,,,
46,VISA PLATINUM,9000,8149.68,0.00,0,244,0.00,Active,Active,0IIAZII1IIIQ,...,,,,,,,,,,
47,VISA PLATINUM,2000,83.90,83.90,0,29,0.00,Active,Active,AZZQQZZQ%-ZZ,...,,,,,,,,,,
48,VISA PLATINUM,2000,0.00,0.00,0,0,0.00,Active,Active,ZZQQZZQ%-ZZZ,...,,,,,,,,,,

In [60]:
for index, row in imp_Cardtypefeatures.iterrows():
    item_len = len(row['ActivityHistory1_12'])
    item = row['ActivityHistory1_12']
    for i in range(item_len):
        target_row_name = 'ActivityHistory_' + str(i+1)
        imp_Cardtypefeatures.at[index,target_row_name] = dict[item[i]]
#         row[target_row_name] = dict[item[i]]
imp_Cardtypefeatures

,CardType,CreditLine,LastStatementBalanceAmount,LastStatementPurchaseAmount,LastStatementPurchaseReturnAmount,LastStatementMinimumPaymentDueAmount,LastStatementPaymentTotalAmount,CardExternalStatus,CardInternalStatus,ActivityHistory1_12,...,ActivityHistory_3,ActivityHistory_4,ActivityHistory_5,ActivityHistory_6,ActivityHistory_7,ActivityHistory_8,ActivityHistory_9,ActivityHistory_10,ActivityHistory_11,ActivityHistory_12
0,VISA PLATINUM,18000,4710.24,0.00,0,141,1000.00,Active,Active,IIIIIIIIIIII,...,50,50,50,50,50,50,50,50,50,50
1,VISA PLATINUM,18000,5672.74,0.00,0,0,1000.00,Active,Active,IIIIIIIIIIII,...,50,50,50,50,50,50,50,50,50,50
2,VISA PLATINUM,18000,6628.99,0.00,0,199,1000.00,Active,Active,IIIIIIIIIIII,...,50,50,50,50,50,50,50,50,50,50
3,VISA PLATINUM,18000,7577.10,0.00,0,0,1000.00,Active,Active,IIIIIIIIIIII,...,50,50,50,50,50,50,50,50,50,50
4,VISA PLATINUM,18000,8518.43,0.00,0,256,1000.00,Active,Active,IIIIIIIIIIII,...,50,50,50,50,50,50,50,50,50,50
5,VISA PLATINUM,18000,9453.96,0.00,0,284,600.00,Active,Active,IIIIIIIIIIII,...,50,50,50,50,50,50,50,50,50,50
6,VISA PLATINUM,18000,9983.57,0.00,0,300,500.00,Active,Active,IIIIIIIIIIII,...,50,50,50,50,50,50,50,50,50,50
7,VISA PLATINUM,18000,10409.66,0.00,0,0,500.00,Active,Active,IIIIIIIIIIII,...,50,50,50,50,50,50,50,50,50,50
8,VISA PLATINUM,18000,10832.62,0.00,0,325,400.00,Active,Active,IIIIIIIIIIII,...,50,50,50,50,50,50,50,50,50,50
9,VISA PLATINUM,18000,11152.88,0.00,0,335,400.00,Active,Active,IIIIIIIIIIII,...,50,50,50,50,50,50,50,50,50,50
10,VISA PLATINUM,18000,11470.92,0.00,0,344,352.00,Active,Active,IIIIIIIIIIII,...,50,50,50,50,50,50,50,50,50,50
11,VISA PLATINUM,18000,11738.51,0.00,0,352,500.00,Active,Active,IIIIIIIIIIIA,...,50,50,50,50,50,50,50,50,50,20
12,VISA PLATINUM,18000,12218.70,0.00,0,367,500.00,Active,Active,IIIIIIIIIIA,...,50,50,50,50,50,50,50,50,20,
13,VISA PLATINUM,18000,12698.08,0.00,0,0,500.00,Active,Active,IIIIIIIIIA,...,50,50,50,50,50,50,50,20,,
14,VISA PLATINUM,18000,13176.73,0.00,0,395,500.00,Active,Active,IIIIIIIIA,...,50,50,50,50,50,50,20,,,
15,VISA PLATINUM,18000,13654.55,0.00,0,0,500.00,Active,Active,IIIIIIIA,...,50,50,50,50,50,20,,,,
16,VISA PLATINUM,18000,14131.54,0.00,0,424,500.00,Active,Active,IIIIIIA,...,50,50,50,50,20,,,,,
17,VISA PLATINUM,18000,14607.60,0.00,0,438,500.00,Active,Active,IIIIIA,...,50,50,50,20,,,,,,
18,VISA PLATINUM,18000,15083.03,0.00,0,452,480.00,Active,Active,IIIIA,...,50,50,20,,,,,,,
19,VISA PLATINUM,18000,15537.53,0.00,0,0,480.00,Active,Active,IIIA,...,50,20,,,,,,,,
20,VISA PLATINUM,18000,15991.29,0.00,0,480,494.00,Active,Active,IIA,...,20,,,,,,,,,
21,VISA PLATINUM,18000,16458.26,0.00,0,494,508.00,Active,Active,IA,...,,,,,,,,,,
22,VISA PLATINUM,9000,1060.12,44.95,0,32,250.00,Active,Active,QQAQQQQQQA%%,...,20,40,40,40,40,40,40,20,10,10
23,VISA PLATINUM,9000,1256.64,211.38,0,0,300.00,Active,Active,QAQQQQQQA%%%,...,40,40,40,40,40,40,20,10,10,10
24,VISA PLATINUM,9000,1334.93,206.23,0,40,0.00,Active,Active,AQQQQQQA%%%-,...,40,40,40,40,40,20,10,10,10,40
25,VISA PLATINUM,9000,1119.94,738.70,0,0,50.00,Active,Active,QQQQQQA%%%-0,...,40,40,40,40,20,10,10,10,40,10
26,VISA PLATINUM,9000,425.59,161.10,0,27,160.00,Active,Active,QQQQQA%%%-0I,...,40,40,40,20,10,10,10,40,10,50
27,VISA PLATINUM,9000,421.67,324.00,0,27,100.00,Active,Active,QQQQA%%%-0II,...,40,40,20,10,10,10,40,10,50,50
28,VISA PLATINUM,9000,196.28,21.62,0,27,300.00,Active,Active,QQQA%%%-0IIQ,...,40,20,10,10,10,40,10,50,50,40
29,VISA PLATINUM,9000,472.40,131.44,0,0,100.00,Active,Active,QQA%%%-0IIQQ,...,20,10,10,10,40,10,50,50,40,40
30,VISA PLATINUM,9000,437.83,267.51,0,27,100.00,Active,Active,QA%%%-0IIQQQ,...,10,10,10,40,10,50,50,40,40,40
31,VISA PLATINUM,9000,267.61,268.81,0,27,0.00,Active,Active,A%%%-0IIQQQQ,...,10,10,40,10,50,50,40,40,40,40
32,VISA PLATINUM,9000,-1.20,0.00,0,0,0.00,Active,Credit Balance,%%%-0IIQQQQI,...,10,40,10,50,50,40,40,40,40,50
33,VISA PLATINUM,9000,-1.20,0.00,0,0,0.00,Active,Credit Balance,%%-0IIQQQQII,...,40,10,50,50,40,40,40,40,50,50
34,VISA PLATINUM,9000,-1.20,0.00,0,0,0.00,Active,Credit Balance,%-0IIQQQQIII,...,10,50,50,40,40,40,40,50,50,50
35,VISA PLATINUM,9000,-1.20,0.00,0,0,765.81,Active,Credit Balance,-0IIQQQQIII0,...,50,50,40,40,40,40,50,50,50,10
36,VISA PLATINUM,9000,763.04,0.00,0,27,0.00,Active,Credit Balance,0IIQQQQIII0I,...,50,40,40,40,40,50,50,50,10,50
37,VISA PLATINUM,9000,755.42,0.00,0,0,40.00,Active,Active,IIQQQQIII0II,...,40,40,40,40,50,50,50,10,50,50
38,VISA PLATINUM,9000,787.60,0.00,0,27,30.00,Active,Active,IQQQQIII0IIA,...,40,40,40,50,50,50,10,50,50,20
39,VISA PLATINUM,9000,812.14,363.10,0,27,60.00,Active,Active,QQQQIII0IIAZ,...,40,40,50,50,50,10,50,50,20,0
40,VISA PLATINUM,9000,506.48,502.61,0,27,7541.20,Active,Active,QQQIII0IIAZI,...,40,50,50,50,10,50,50,20,0,50
41,VISA PLATINUM,9000,7541.20,375.73,0,0,250.00,Active,Active,QQIII0IIAZII,...,50,50,50,10,50,50,20,0,50,50
42,VISA PLATINUM,9000,7396.55,222.85,0,222,230.00,Active,Active,QIII0IIAZII1,...,50,50,10,50,50,20,0,50,50,-150
43,VISA PLATINUM,9000,7391.34,0.00,0,222,300.00,Active,Active,III0IIAZII1I,...,50,10,50,50,20,0,50,50,-150,50
44,VISA PLATINUM,9000,7678.81,0.00,0,230,237.00,Active,Active,II0IIAZII1II,...,10,50,50,20,0,50,50,-150,50,50
45,VISA PLATINUM,9000,7902.97,0.00,0,237,260.00,Active,Active,I0IIAZII1III,...,50,50,20,0,50,50,-150,50,50,50
46,VISA PLATINUM,9000,8149.68,0.00,0,244,0.00,Active,Active,0IIAZII1IIIQ,...,50,20,0,50,50,-150,50,50,50,40
47,VISA PLATINUM,2000,83.90,83.90,0,29,0.00,Active,Active,AZZQQZZQ%-ZZ,...,0,40,40,0,0,40,10,40,0,0
48,VISA PLATINUM,2000,0.00,0.00,0,0,0.00,Active,Active,ZZQQZZQ%-ZZZ,...,40,40,0,0,40,10,40,0,0,0