# Finding the important dataset

In [1]:
import pandas as pd

In [22]:
df = pd.read_csv("dataset.csv")
# df.columns

# Separating the important features from the original dataset

In [90]:
imp_Cardtypefeatures = df. loc [:, [
                             'CardType',
                             'CreditLine',
                             'LastStatementBalanceAmount',
                             'LastStatementPurchaseAmount', 
                             'LastStatementPurchaseReturnAmount',
                             'LastStatementMinimumPaymentDueAmount',
                             'LastStatementPaymentTotalAmount',
                             'CardExternalStatus',
                             'CardInternalStatus',
                             'ActivityHistory1_12',
                             'DelinquentDaysCount',
                             'DelinquentTotalAmount',
                             'LifetimeDelinquent1CycleCount',
                             'LifetimeDelinquent2CycleCount',
                             'LifetimeDelinquent3CycleCount',
                             'LifetimeDelinquent4CycleCount',
                             'LifetimeDelinquent5CycleCount',
                             'LifetimeDelinquent6CycleCount',
                             'LifetimeDelinquent7CycleCount',
                             'ChargeOffAmount',
                              'Target'
]
                            ]

In [91]:
imp_Cardtypefeatures

,CardType,CreditLine,LastStatementBalanceAmount,LastStatementPurchaseAmount,LastStatementPurchaseReturnAmount,LastStatementMinimumPaymentDueAmount,LastStatementPaymentTotalAmount,CardExternalStatus,CardInternalStatus,ActivityHistory1_12,...,DelinquentTotalAmount,LifetimeDelinquent1CycleCount,LifetimeDelinquent2CycleCount,LifetimeDelinquent3CycleCount,LifetimeDelinquent4CycleCount,LifetimeDelinquent5CycleCount,LifetimeDelinquent6CycleCount,LifetimeDelinquent7CycleCount,ChargeOffAmount,Target
0,VISA PLATINUM,18000.0,4710.24,0.0,0.0,141.0,1000.0,Active,Active,IIIIIIIIIIII,...,0.0,0,0,0,0,0,0,0,0.0,0
1,VISA PLATINUM,18000.0,5672.74,0.0,0.0,0.0,1000.0,Active,Active,IIIIIIIIIIII,...,0.0,0,0,0,0,0,0,0,0.0,0
2,VISA PLATINUM,18000.0,6628.99,0.0,0.0,199.0,1000.0,Active,Active,IIIIIIIIIIII,...,0.0,0,0,0,0,0,0,0,0.0,0
3,VISA PLATINUM,18000.0,7577.10,0.0,0.0,0.0,1000.0,Active,Active,IIIIIIIIIIII,...,0.0,0,0,0,0,0,0,0,0.0,0
4,VISA PLATINUM,18000.0,8518.43,0.0,0.0,256.0,1000.0,Active,Active,IIIIIIIIIIII,...,0.0,0,0,0,0,0,0,0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1236968,VISA PREMIER CASH,14000.0,0.00,0.0,0.0,0.0,0.0,Active,Active,ZZZZZZZZZZZZ,...,0.0,0,0,0,0,0,0,0,0.0,0
1236969,VISA PREMIER CASH,14000.0,0.00,0.0,0.0,0.0,0.0,Active,Active,ZZZZZZZZZZZZ,...,0.0,0,0,0,0,0,0,0,0.0,0
1236970,VISA PREMIER CASH,10000.0,0.00,0.0,0.0,0.0,0.0,Active,Active,ZZZZZZZZZZZZ,...,0.0,0,0,0,0,0,0,0,0.0,0
1236971,VISA PREMIER CASH,10000.0,0.00,0.0,0.0,0.0,0.0,Active,Active,ZZZZZZZZZZZZ,...,0.0,0,0,0,0,0,0,0,0.0,0
1236972,VISA PREMIER CASH,10000.0,0.00,0.0,0.0,0.0,0.0,Active,Active,ZZZZZZZZZZZZ,...,0.0,0,0,0,0,0,0,0,0.0,0

In [36]:
# df

In [93]:
# result = []
for i in range(12):
#     print(i)
    save_str = ("ActivityHistory_%2d" % (i+1)).replace(' ', '')
    imp_Cardtypefeatures[save_str] = ""
imp_Cardtypefeatures

,CardType,CreditLine,LastStatementBalanceAmount,LastStatementPurchaseAmount,LastStatementPurchaseReturnAmount,LastStatementMinimumPaymentDueAmount,LastStatementPaymentTotalAmount,CardExternalStatus,CardInternalStatus,ActivityHistory1_12,...,ActivityHistory_3,ActivityHistory_4,ActivityHistory_5,ActivityHistory_6,ActivityHistory_7,ActivityHistory_8,ActivityHistory_9,ActivityHistory_10,ActivityHistory_11,ActivityHistory_12
0,VISA PLATINUM,18000.0,4710.24,0.0,0.0,141.0,1000.0,Active,Active,IIIIIIIIIIII,...,,,,,,,,,,
1,VISA PLATINUM,18000.0,5672.74,0.0,0.0,0.0,1000.0,Active,Active,IIIIIIIIIIII,...,,,,,,,,,,
2,VISA PLATINUM,18000.0,6628.99,0.0,0.0,199.0,1000.0,Active,Active,IIIIIIIIIIII,...,,,,,,,,,,
3,VISA PLATINUM,18000.0,7577.10,0.0,0.0,0.0,1000.0,Active,Active,IIIIIIIIIIII,...,,,,,,,,,,
4,VISA PLATINUM,18000.0,8518.43,0.0,0.0,256.0,1000.0,Active,Active,IIIIIIIIIIII,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1236968,VISA PREMIER CASH,14000.0,0.00,0.0,0.0,0.0,0.0,Active,Active,ZZZZZZZZZZZZ,...,,,,,,,,,,
1236969,VISA PREMIER CASH,14000.0,0.00,0.0,0.0,0.0,0.0,Active,Active,ZZZZZZZZZZZZ,...,,,,,,,,,,
1236970,VISA PREMIER CASH,10000.0,0.00,0.0,0.0,0.0,0.0,Active,Active,ZZZZZZZZZZZZ,...,,,,,,,,,,
1236971,VISA PREMIER CASH,10000.0,0.00,0.0,0.0,0.0,0.0,Active,Active,ZZZZZZZZZZZZ,...,,,,,,,,,,
1236972,VISA PREMIER CASH,10000.0,0.00,0.0,0.0,0.0,0.0,Active,Active,ZZZZZZZZZZZZ,...,,,,,,,,,,

##### Dictionary to assign values related to the activityhistory1_12 feature

In [ ]:
dict = {
     0   : "10",
     1   : "-150",
     2   : "-160",
     3   : "-170",
     4   : "-180",
     5   : "-190",
     6   : "200",
     7   : "210",
    "A" : "20",
    "B" : "-220",
    "C" : "-230",
    "D" : "-240",
    "E" : "-250",
    "F" : "-260",
    "G" : "-270",
    "H" : "-280",
    "I" : "50",
    "J" : "-10",
    "K" : "-20",
    "L" : "-30",
    "M" : "-40",
    "N" : "-50",
    "O" : "-60",
    "P" :"-70",
    "Q" : "40",
    "R" : "-80",
    "S" : "-90",
    "T" : "-100",
    "U" : "-110",
    "V" : "-120",
    "W" : "-130",
    "X" : "-140",
    "Z" : "0",
    "%" : "10",
    "#" : "20", 
    "+" : "30",
    "-" : "40"    
}

In [94]:
# dict

{0: '10',
 1: '-150',
 2: '-160',
 3: '-170',
 4: '-180',
 5: '-190',
 6: '200',
 7: '210',
 'A': '20',
 'B': '-220',
 'C': '-230',
 'D': '-240',
 'E': '-250',
 'F': '-260',
 'G': '-270',
 'H': '-280',
 'I': '50',
 'J': '-10',
 'K': '-20',
 'L': '-30',
 'M': '-40',
 'N': '-50',
 'O': '-60',
 'P': '-70',
 'Q': '40',
 'R': '-80',
 'S': '-90',
 'T': '-100',
 'U': '-110',
 'V': '-120',
 'W': '-130',
 'X': '-140',
 'Z': '0',
 '%': '10',
 '#': '20',
 '+': '30',
 '-': '40'}